### ISSUE TITLE
אפשרות להגדיר אישור או הקלטה מחדש בזיהוי דיבור

### ISSUE THREAD

**Issue by eliezerbloy** [ShlomoCode/yemot-router2#46]
קודם כל תודה ענקית על הספרייה המעולה!!

בפונקציה read, ב-mode stt, נראה שחסר את ההגדרות של **מה לעשות לאחר המרת הדיבור**.
אני מעתיק מתוך התיעוד של ימות:

> מה לעשות לאחר המרת הדיבור
אם מעוניינים שלא יושמע ללקוח את ההקראה של הטקסט שהתקבל לצורך שיקוף יש להגדיר

`api_say_tts=no`

> אישור הזיהוי
> ברירת מחדל לאחר ההשמעה (שיקוף ההקלטה בהקלטה מהטקסט) מיד עובר לשלב הבא,
> אם רוצים שיבקש אישור, או אפשרות להקליט מחדש ניתן להגדיר

`api_voice_ask_ok=yes`

> שמירת הקלטה
> אם רוצים שהקובץ של ההקלטה יישאר אצלכם במערכת יש להגדיר

`api_save_file=yes`

> הקובץ נשמר זמנית בסל המחזור בתוך תיקיה ApiVoice

**Comment by ShlomoCode** [comment]
אלו הגדרות שמגדירים בהגדרת השלוחה מערכת הטלפונית ולא בתשובת הAPI מהשרת ולכן הן לא רלוונטיות לספריה הזאת.
